version: 2
jobs:
  build:
    working_directory: ~/mandelbrot
    docker:
      - image: circleci/clojure:lein-2.9.1
    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          keys:
            - mandelbrot-{{ checksum "project.clj" }}
            - mandelbrot-
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: mandelbrot-{{ checksum "project.clj" }}
      - run: ls
      - run: chmod -R -rw docs
      - run: lein test
